export const LOCATIONS_LIST = [
    { name: "New York", flag: "us", code: "NY" },
    { name: "Los Angeles", flag: "us", code: "LA" },
    { name: "Chicago", flag: "us", code: "CHI" },
    { name: "Dallas", flag: "us", code: "DAL" },
    { name: "Buffalo", flag: "us", code: "BUF" },
    { name: "Miami", flag: "us", code: "MIA" },
    { name: "Atlanta", flag: "us", code: "ATL" },
    { name: "Seattle", flag: "us", code: "SEA" },
    { name: "San Jose", flag: "us", code: "SJC" },
    { name: "Amsterdam", flag: "nl", code: "AMS" },
    { name: "Newcastle", flag: "gb", code: "NCL" },
    { name: "London", flag: "gb", code: "LON" },
    { name: "Manchester", flag: "gb", code: "MAN" },
    { name: "Edinburgh", flag: "gb", code: "EDI" },
    { name: "Glasgow", flag: "gb", code: "GLA" },
    { name: "Birmingham", flag: "gb", code: "BHX" },
    { name: "Frankfurt", flag: "de", code: "FRA" },
    { name: "Paris", flag: "fr", code: "PAR" },
    { name: "Singapore", flag: "sg", code: "SG" },
    { name: "Tokyo", flag: "jp", code: "TYO" },
    { name: "Sydney", flag: "au", code: "SYD" },
    { name: "Toronto", flag: "ca", code: "TOR" },
    { name: "Montreal", flag: "ca", code: "MTL" },
    { name: "Vancouver", flag: "ca", code: "VAN" },
    { name: "Calgary", flag: "ca", code: "YYC" },
    { name: "Ottawa", flag: "ca", code: "YOW" },
    { name: "Sao Paulo", flag: "br", code: "SAO" },
    { name: "Mumbai", flag: "in", code: "BOM" },
    { name: "Hong Kong", flag: "hk", code: "HKG" },
    { name: "Johannesburg", flag: "za", code: "JNB" },
    { name: "Dubai", flag: "ae", code: "DXB" },
    { name: "Moscow", flag: "ru", code: "MOW" },
    { name: "Stockholm", flag: "se", code: "STO" },
    { name: "Oslo", flag: "no", code: "OSL" },
];