export const RUST_PLANS = [
  {
    name: "Starter",
    description: "Recommended for 40 Players",
    priceGBP: 5.75,
    period: "month",
    features: [
      "AMD Ryzen™ 9 5900X",
      "8 GB DDR4 RAM",
      "150GB SSD Storage",
      "DDoS Protection",
      "Newcastle, United Kingdom",
      "10 MySQL Databases",
      "BytePanel (Game Panel)",
      "Oxide/Umod Supported",
      "Rust+ Supported",
      "99.6% Uptime SLA",
    ],
  },
  {
    name: "Standard",
    description: "Recommended for 75 Players",
    priceGBP: 8.95,
    period: "month",
    popular: true,
    features: [
      "AMD Ryzen™ 9 5900X",
      "12 GB DDR4 RAM",
      "200GB SSD Storage",
      "DDoS Protection",
      "Newcastle, United Kingdom",
      "10 MySQL Databases",
      "BytePanel (Game Panel)",
      "Oxide/Umod Supported",
      "Rust+ Supported",
      "99.6% Uptime SLA",
    ],
  },
  {
    name: "Performance",
    description: "Recommended for 100 Players",
    priceGBP: 12.75,
    period: "month",
    features: [
      "AMD Ryzen™ 9 5900X",
      "16 GB DDR4 RAM",
      "250GB SSD Storage",
      "DDoS Protection",
      "Newcastle, United Kingdom",
      "10 MySQL Databases",
      "BytePanel (Game Panel)",
      "Oxide/Umod Supported",
      "Rust+ Supported",
      "99.6% Uptime SLA",
    ],
  },
]